{{- $gateway := .Values.gateway -}}
{{- $ui := .Values.ui -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "curriculum-forge.fullname" . }}-gateway
  labels:
    {{- include "curriculum-forge.labels" . | nindent 4 }}
    component: gateway
spec:
  type: {{ $gateway.service.type }}
  ports:
    - port: {{ $gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq $gateway.service.type "NodePort") $gateway.service.nodePort }}
      nodePort: {{ $gateway.service.nodePort }}
      {{- end }}
  selector:
    {{- include "curriculum-forge.selectorLabels" . | nindent 4 }}
    component: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "curriculum-forge.fullname" . }}-ui
  labels:
    {{- include "curriculum-forge.labels" . | nindent 4 }}
    component: ui
spec:
  type: {{ $ui.service.type }}
  ports:
    - port: {{ $ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq $ui.service.type "NodePort") $ui.service.nodePort }}
      nodePort: {{ $ui.service.nodePort }}
      {{- end }}
  selector:
    {{- include "curriculum-forge.selectorLabels" . | nindent 4 }}
    component: ui
